<?php
declare(strict_types=1);
?>

<ul>
<?php
/**
 * This is pretty straight forward. It simply take the array
 * of validation messages and formats them for display
 */
foreach ($errors as $element => $messages):
?>
    <li>
        <?=$element?>
        <ul>
            <?php
            foreach ($messages as $key => $message):
            ?>
            <li><?=$message?></li>
            <?php
            endforeach;
            ?>
        </ul>
    </li>
<?php
endforeach;
?>
</ul>