<section id="hero" class="d-flex align-items-center">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 d-flex flex-column justify-content-center pt-4 pt-lg-0 order-2 order-lg-1" data-aos="fade-up" data-aos-delay="200">
                <h1><?=$this->heading ?? '';?></h1>
                <h2><?=$this->blurb ?? '';?></h2>
                <?php if ($this->enableHeroVideo): ?>
                <div class="d-flex justify-content-center justify-content-lg-start">
                    <a href="#about" class="btn-get-started scrollto">Get Started</a>
                    <a href="<?=$this->videoLink ?? '';?>" class="glightbox btn-watch-video"><i class="bi bi-play-circle"></i><span>Watch Video</span></a>
                </div>
                <?php endif; ?>
            </div>
            <div class="col-lg-6 order-1 order-lg-2 hero-img" data-aos="zoom-in" data-aos-delay="200">
                <img src="assets/img/<?=$this->img ?? '';?>" class="img-fluid animated" alt="">
            </div>
        </div>
    </div>
</section>