<?php

declare(strict_types=1);

?>
<nav id="navbar" class="navbar">
    <ul>
        <?php
        // $linkById is true then we want an active link only when we are at #hero
            $linkById = $this->singlePage && $this->showOnHome !== [];
        ?>
        <li><a class="<?= ! $linkById ? 'nav-link active' : 'nav-link scrollto';?>" href="<?=$linkById ? '#hero' : $this->url('home');?>">Home</a></li>
        <?php
        foreach ($this->activeLinks as $link):
        ?>
            <?php if (in_array($link, $this->showOnHome)): ?>
                <li><a class="<?=$link['title'] === $this->currentRoute ? 'nav-link scrollto active' : 'nav-link scrollto';?>" href="<?=$link['sectionId']?>"><?=ucfirst($link['title']);?></a></li>
            <?php else: ?>
                <?php if (
                        $this->user !== null
                        && $link['title'] === 'login'
                        && $this->settings->enableLogin
                        && ! $this->settings->enableLoginModal
                    ): ?>
                    <li><a class="<?=$link['title'] === $this->currentRoute ? 'nav-link active' : 'nav-link';?>" href="<?=$this->url('logout')?>">Logout</a></li>
                <?php elseif(
                        $link === 'login'
                        && $this->settings->enableLogin
                        && ! $this->settings->enableLoginModal
                    ): ?>
                    <li><a class="<?=$link['title'] === $this->currentRoute ? 'nav-link active' : 'nav-link';?>" href="/<?=$link['title'];?>"><?=ucfirst($link['title']);?></a></li>
                <?php elseif(
                        $link['title'] === 'login'
                        && $this->settings->enableLogin
                        && $this->settings->enableLoginModal
                    ): ?>
                    <li><a id="open-login-modal" class="<?=$link['title'] === $this->currentRoute ? 'nav-link active' : 'nav-link';?>" href="#"><?=ucfirst($link['title']);?></a></li>
                <?php endif; ?>
            <?php endif; ?>
        <?php
        endforeach;
        ?>
        <?php
        // disable support for this for the moment
        if ($this->settings->enableDropDownMenu) {
            $this->settings->enableDropDownMenu = false;
        }
        if ($this->settings->enableDropDownMenu):
            // a config for this, array interiorPages
        ?>
        <li class="dropdown"><a href="#"><span>Drop Down</span> <i class="bi bi-chevron-down"></i></a>
            <ul>
                <li><a href="#">Drop Down 1</a></li>
                <li class="dropdown"><a href="#"><span>Deep Drop Down</span> <i class="bi bi-chevron-right"></i></a>
                <ul>
                    <li><a href="#">Deep Drop Down 1</a></li>
                    <li><a href="#">Deep Drop Down 2</a></li>
                    <li><a href="#">Deep Drop Down 3</a></li>
                    <li><a href="#">Deep Drop Down 4</a></li>
                    <li><a href="#">Deep Drop Down 5</a></li>
                </ul>
                </li>
                <li><a href="#">Drop Down 2</a></li>
                <li><a href="#">Drop Down 3</a></li>
                <li><a href="#">Drop Down 4</a></li>
            </ul>
        </li>
        <?php
        endif;
        ?>
    </ul>
    <i class="bi bi-list mobile-nav-toggle"></i>
</nav><!-- .navbar -->