<?php

declare(strict_types=1);

?>
<nav id="navbar" class="navbar">
    <ul>
        <?php
        // $linkById is true then we want an active link only when we are at #hero
            $linkById = $this->singlePage && $this->showOnHome !== [];
        ?>
        <li><a class="<?= ! $linkById ? 'nav-link active' : 'nav-link scrollto';?>" href="<?=$linkById ? '#hero' : $this->url('home');?>">Home</a></li>
        <?php
        foreach ($this->activeLinks as $link):
        ?>
            <?php if (in_array($link, $this->showOnHome)): ?>
                <li><a class="<?=$link === $this->currentRoute ? 'nav-link scrollto active' : 'nav-link scrollto';?>" href="#<?=$link;?>"><?=ucfirst($link);?></a></li>
            <?php else: ?>
                <?php if (
                        $this->user !== null
                        && $link === 'login'
                        && $this->enableLogin
                        && ! $this->enableLoginModal
                    ): ?>
                    <li><a class="<?=$link === $this->currentRoute ? 'nav-link active' : 'nav-link';?>" href="<?=$this->url('logout')?>">Logout</a></li>
                <?php elseif(
                        $link === 'login'
                        && $this->enableLogin
                        && ! $this->enableLoginModal
                    ): ?>
                    <li><a class="<?=$link === $this->currentRoute ? 'nav-link active' : 'nav-link';?>" href="/<?=$link;?>"><?=ucfirst($link);?></a></li>
                <?php endif; ?>
            <?php endif; ?>
        <?php
        endforeach;
        ?>
        <?php
        if ($this->enableDropDownMenu):
        ?>
        <li class="dropdown"><a href="#"><span>Drop Down</span> <i class="bi bi-chevron-down"></i></a>
            <ul>
                <li><a href="#">Drop Down 1</a></li>
                <li class="dropdown"><a href="#"><span>Deep Drop Down</span> <i class="bi bi-chevron-right"></i></a>
                <ul>
                    <li><a href="#">Deep Drop Down 1</a></li>
                    <li><a href="#">Deep Drop Down 2</a></li>
                    <li><a href="#">Deep Drop Down 3</a></li>
                    <li><a href="#">Deep Drop Down 4</a></li>
                    <li><a href="#">Deep Drop Down 5</a></li>
                </ul>
                </li>
                <li><a href="#">Drop Down 2</a></li>
                <li><a href="#">Drop Down 3</a></li>
                <li><a href="#">Drop Down 4</a></li>
            </ul>
        </li>
        <?php
        endif;
        ?>
    </ul>
    <i class="bi bi-list mobile-nav-toggle"></i>
</nav><!-- .navbar -->