<section id="faq" class="faq section-bg">
    <div class="container" data-aos="fade-up">
        <div class="section-title">
            <h2><?=$this->faqHeading ?? '';?></h2>
            <p><?=$this->faqBlurb ?? '';?></p>
        </div>
        <div class="faq-list">
            <ul>
            <?php if (isset($this->data) && count($this->data) > 0): ?>
              <?php for ($i=0; $i < count($this->data); $i++): $target = $i + 1;?>
                <li data-aos="fade-up" data-aos-delay="<?=$target?>00">
                    <i class="bx bx-help-circle icon-help"></i>
                    <a data-bs-toggle="collapse" class="collapse" data-bs-target="#faq-list-<?=$target?>"><?=$this->data[$i]['question'];?><i class="bx bx-chevron-down icon-show"></i><i class="bx bx-chevron-up icon-close"></i></a>
                    <div id="faq-list-<?=$target?>" class="collapse show" data-bs-parent=".faq-list">
                        <p>
                          <?=$this->data[$i]['answer'];?>
                        </p>
                    </div>
                </li>
              <?php endfor; ?>
            <?php endif; ?>
            </ul>
        </div>
    </div>
</section>