<section id="services" class="services section-bg">
    <div class="container" data-aos="fade-up">
        <div class="section-title">
          <h2><?=$this->serviceHeading ?? '';?></h2>
          <p><?=$this->serviceBlurb ?? '';?></p>
        </div>
        <div class="row">
          <?php if (isset($this->data) && count($this->data) > 0): ?>
            <?php for ($i=0; $i < count($this->data); $i++): $target = $i + 1; ?>
            <div class="col-xl-3 col-md-6 d-flex align-items-stretch" data-aos="zoom-in" data-aos-delay="<?=$this->target?>00">
              <div class="icon-box">
                <div class="icon"><i class="<?=$this->data[$i]['icon'] ?? '';?>"></i></div>
                <h4><a href="<?php $this->data[$i]['link'] ?? '';?>"><?=$this->data[$i]['name'] ?? '';?></a></h4>
                <p><?=$this->data[$i]['content'] ?? '';?></p>
              </div>
            </div>
            <?php endfor; ?>
          <?php endif; ?>
        </div>
    </div>
</section>