<section id="skills" class="skills">
    <div class="container" data-aos="fade-up">
        <div class="row">
            <?php if ($this->skillsImg): ?>
            <div class="col-lg-6 d-flex align-items-center" data-aos="fade-right" data-aos-delay="100">
                <img src="assets/img/<?=$this->skillsImg?>" class="img-fluid" alt="">
            </div>
            <?php endif; ?>
            <div class="col-lg-6 pt-4 pt-lg-0 content" data-aos="fade-left" data-aos-delay="100">
                <h3><?=$this->skillsHeading ?? '';?></h3>
                <p class="fst-italic"><?=$this->skillsBlurb ?? '';?></p>
                <div class="skills-content">
                <?php if (isset($this->data) && count($this->data) > 0): ?>
                  <?php foreach ($this->data as $skill): ?>
                    <div class="progress">
                        <span class="skill">
                          <?=$skill['name'] ?? '';?> <i class="val"><?=$skill['percentage'] ?? '';?>%</i>
                        </span>
                        <div class="progress-bar-wrap">
                            <div class="progress-bar" role="progressbar" aria-valuenow="<?=$skill['percentage'] ?? '';?>" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                    </div>
                  <?php endforeach; ?>
                <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
</section>