<?php

declare(strict_types=1);

/**
 * Note that these do not get added to the buffer until they are echoed
 * All calls up to the point of echoing the helper just adds them to the stack
 * dependent on the call made. I like append since its easier to read.
 *
 * Its important to note here that all of the template files excute within the scope of
 * Laminas\View\Renderer\PhpRenderer
 * I mention this so that you can review that class and see how they use overloading and a plugin manager to
 * provide the helpers. It's a common approach in OO. Sorta like a proxy pattern but not hardcore lol
 *
 * One of the few things left to do is to pass the multi-page flag through to the page models
 * so that when in multi-page mode we can call the headTitle helper and it will append the
 * page title to the base siteName that is passed here.
 *
 * I should also note, that in multi-page mode we could also do things like appending a js file that
 * is needed only in the context of that particular template etc. Stylesheets can be pushed into the stack as well.
 */
$this->headLink()
    ->appendStylesheet('https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Jost:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i')
    ->appendStylesheet('/assets/vendor/aos/aos.css')
    ->appendStylesheet('/assets/vendor/bootstrap/css/bootstrap.min.css')
    ->appendStylesheet('/assets/vendor/bootstrap-icons/bootstrap-icons.css')
    ->appendStylesheet('/assets/vendor/boxicons/css/boxicons.min.css')
    ->appendStylesheet('/assets/vendor/glightbox/css/glightbox.min.css')
    ->appendStylesheet('/assets/vendor/remixicon/remixicon.css')
    ->appendStylesheet('/assets/vendor/swiper/swiper-bundle.min.css')
    ->appendStylesheet('/assets/css/style.css');

$this->inlineScript()
    ->appendFile('/assets/vendor/aos/aos.js')
    ->appendFile('/assets/vendor/bootstrap/js/bootstrap.bundle.min.js')
    ->appendFile('/assets/vendor/glightbox/js/glightbox.min.js')
    ->appendFile('/assets/vendor/isotope-layout/isotope.pkgd.min.js')
    ->appendFile('/assets/vendor/swiper/swiper-bundle.min.js')
    ->appendFile('/assets/vendor/waypoints/noframework.waypoints.js')
    ->appendFile('/assets/vendor/php-email-form/validate.js')
    ->appendFile('/assets/js/main.js')
    ->appendFile('/assets/js/app.js');
?>
<?=$this->doctype()?>
<html>
    <head>
        <base href="/" />
        <?php
        $this->headMeta()
            ->setCharSet('UTF-8')
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
        ?>
        <?=$this->headTitle($this->siteName)->setSeparator(' - ')->setAutoEscape(false)?>
        <?=$this->headMeta()?>
        <?=$this->headLink(
            [
                'rel'  => 'shortcut icon',
                'type' => 'image/png',
                'href' => '/assets/img/favicon.png',
            ]
        )?>
    </head>
    <body class="app">
        <!-- ======= Header ======= -->
        <header id="header" class="<?=$this->isHome ? 'fixed-top' : 'fixed-top header-inner-pages'; ?>">
            <div class="container d-flex align-items-center">
                <h1 class="logo me-auto"><a href="/"><?=$this->siteName?></a></h1>
                <!-- Uncomment below if you prefer to use an image logo -->
                <!-- <a href="index.html" class="logo me-auto"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
                <!-- nav -->
                <?php if ($this->user): ?>
                    <button id="open-settings-modal" type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@fat">Manage Settings</button>
                    <?php endif; ?>
                <?php
                    if (isset($this->nav)) {
                        echo $this->render($this->nav);
                    }
                ?>
                <!-- nav -->
            </div>
        </header><!-- End Header -->
        <!-- ======= Hero Section ======= -->
        <?php
        if (isset($this->hero)) {
            echo $this->render($this->hero);
        }
        ?>
        <!-- End Hero -->
        <!-- Main Section-->
        <main id="main">
            <?php if (! $this->isHome): ?>
                <!-- ======= Breadcrumbs ======= -->
            <section id="breadcrumbs" class="breadcrumbs">
                <div class="container">
                    <ol>
                        <li><a href="/">Home</a></li>
                        <li><?=ucfirst($this->currentRoute)?></li>
                    </ol>
                        <h2><?=ucfirst($this->currentRoute)?></h2>
                </div>
            </section><!-- End Breadcrumbs -->
            <?php endif; ?>
            <?php
                // render the handler templates
                echo $this->content;
            ?>
        </main><!-- End #main -->
        <!-- ======= Footer ======= -->
        <?php
            if (isset($this->footer)) {
                echo $this->render($this->footer);
            }
        ?>
        <!-- End Footer -->
        <div id="preloader"></div>
        <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>
        <?php
        if (isset($this->loginModal)) {
            echo $this->render($this->loginModal);
        }
        ?>
        <!-- print the js stuff -->
        <?=$this->inlineScript()?>
    </body>
</html>
