<?php
$this->headLink()
->appendStylesheet('https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Jost:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i')
->appendStylesheet('/assets/vendor/aos/aos.css')
->appendStylesheet('/assets/vendor/bootstrap/css/bootstrap.min.css')
->appendStylesheet('/assets/vendor/bootstrap-icons/bootstrap-icons.css')
->appendStylesheet('/assets/vendor/boxicons/css/boxicons.min.css')
->appendStylesheet('/assets/vendor/glightbox/css/glightbox.min.css')
->appendStylesheet('/assets/vendor/remixicon/remixicon.css')
->appendStylesheet('/assets/vendor/swiper/swiper-bundle.min.css')
->appendStylesheet('/assets/css/style.css');

$this->inlineScript()
->appendFile('/assets/vendor/aos/aos.js')
->appendFile('/assets/vendor/bootstrap/js/bootstrap.bundle.min.js')
->appendFile('/assets/vendor/glightbox/js/glightbox.min.js')
->appendFile('/assets/vendor/isotope-layout/isotope.pkgd.min.js')
->appendFile('/assets/vendor/swiper/swiper-bundle.min.js')
->appendFile('/assets/vendor/waypoints/noframework.waypoints.js')
->appendFile('/assets/vendor/php-email-form/validate.js')
->appendFile('/assets/js/main.js');
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="shortcut icon" href="https://getlaminas.org/images/favicon/favicon.ico" />
    <?=$this->headTitle('mezzio')->setSeparator(' - ')->setAutoEscape(false)?>
    <?=$this->headMeta()?>
    <?=$this->headLink()?>
</head>
<body class="app">
  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top ">
    <div class="container d-flex align-items-center">

      <h1 class="logo me-auto"><a href="index.html"><?=$this->siteName?></a></h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html" class="logo me-auto"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

      <?php
      if (isset($this->nav)):
      ?>
      <?=$this->render($this->nav)?>
      <?php
      endif;
      ?>

    </div>
  </header><!-- End Header -->

  <!-- ======= Hero Section ======= -->
  <?php
    if (isset($this->hero)) {
        echo $this->render($this->hero);
    }
  ?>
  <!-- End Hero -->

  <main id="main">

    <?php
    if (! $this->multiPage):
    ?>
    <?php
    /**
     * Note these are rendered in the order in which they are defined in the template settings.
     */
    if (isset($this->enabledPages) && count($this->enabledPages) >= 1):
        foreach ($this->enabledPages as $page):
    ?>
            <?=$this->render($this->{$page})?>
    <?php
        endforeach;
    endif;
    ?>

    <?php
    else:
    ?>
    <?=$this->content?>
    <?php
    endif;
    ?>

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  <?php
        if (isset($this->footer)) {
            echo $this->render($this->footer);
        }
  ?>
  <!-- End Footer -->

  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>
    <!-- print the js stuff -->
    <?=$this->inlineScript()?>
</body>
</html>
